name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Run on main by default Sunday morning at 3:30 to check for dependency changes:
    - cron: "30 3 * * 0"

jobs:
  ci:
    name: CI
    uses: molssi-seamm/devops/.github/workflows/CI.yaml@main
    with:
      src : gaussian_step
